SELECT
IFNULL(StructureType,'TBC') AS StructureType,
IFNULL(StreetName,'TBC')AS StreetName,
IFNULL(City,'TBC')AS City,
IFNULL(County,'TBC') AS County,
IFNULL(LOC_PAGE,'TBC') AS LOC_PAGE,
IFNULL(LOC_LONG,'TBC') AS LOC_LONG,
IFNULL(LOC_LAT,'TBC') AS LOC_LAT,
IFNULL(APN,'TBC') AS APN,
IFNULL(Fault,'TBC') AS Fault,
IFNULL(SiteNumber,'TBC') AS StreetNumber,
IFNULL(TOMBROBOX,'TBC') AS TOMBROBOX
FROM all_project_information
ORDER BY StructureType ASC
